
development:
  adapter: postgresql
  encoding: unicode
  database: emacsconf_dev
  username: emacsconf
  pool: 5

test: &test
  adapter: postgresql
  database: emacsconf_test
  username: emacsconf
  pool: 5

production:
  adapter: postgresql
  database: emacsconf_prod
  username: emacsconf
  pool: 5

cucumber:
  <<: *test
